<?php


/**
 * Author: Amir Hossein Jahani | iAmir.net
 * Last modified: 9/22/20, 12:25 PM
 * Copyright (c) 2021. Powered by iamir.net
 */

namespace iLaravel\iLogs\iApp\Http\Exceptions;

use Exception;
use iLaravel\iLogs\Vendor\Submit;

class ExceptionHandler extends \iLaravel\Core\iApp\Exceptions\ExceptionHandler
{
   public function render($request, Exception $exception)
   {
       $log = Submit::Log($request, $exception->getMessage(), true);
       return parent::render($request, $exception, $log); // TODO: Change the autogenerated stub
   }
}
