<?php


/**
 * Author: Amir Hossein Jahani | iAmir.net
 * Last modified: 9/22/20, 12:25 PM
 * Copyright (c) 2021. Powered by iamir.net
 */

namespace iLaravel\iLogs\iApp\Http\Exceptions;

use iLaravel\iLogs\Vendor\Submit;
use Throwable;

class ExceptionHandler7 extends \iLaravel\Core\iApp\Exceptions\ExceptionHandler7
{
    public function render($request, Throwable $exception)
    {
        $log = Submit::Log($request, $exception->getMessage(), true);
        return parent::render($request, $exception, $log); // TODO: Change the autogenerated stub
    }
}
